-- init_duckdb.sql
-- SQL to configure DuckDB for accessing Iceberg tables via MinIO.
--
-- NOTE: DuckDB extensions and S3 credentials are configured via the database
-- connection's extra.engine_params.connect_args in Superset, so they are
-- applied automatically on every new connection. This file documents the
-- expected configuration and can be run manually in SQL Lab if needed.
--
-- S3/MinIO credentials are set via connect_args.config:
--   s3_access_key_id, s3_secret_access_key, s3_endpoint, etc.
--
-- Extensions loaded via connect_args.preload_extensions:
--   iceberg, httpfs
--
-- To query Iceberg tables, use iceberg_scan():
--   SELECT * FROM iceberg_scan('s3://warehouse/gold/daily_trading_summary')
--   SELECT * FROM iceberg_scan('s3://warehouse/silver/trades')
--   SELECT * FROM iceberg_scan('s3://warehouse/dimensions/dim_symbol')

-- ─── Example: Gold layer query ─────────────────────────────────────────────
-- SELECT
--     symbol,
--     trading_date AS trade_date,
--     open_price, close_price, high_price, low_price,
--     vwap, total_volume, trade_count, total_value,
--     company_name, sector,
--     ROUND((close_price - open_price) / NULLIF(open_price, 0) * 100, 4) AS change_pct
-- FROM iceberg_scan('s3://warehouse/gold/daily_trading_summary');

-- ─── Alternative: ATTACH-based approach (per-session, not auto-configured) ──
-- Run these manually in SQL Lab if you prefer the catalog-style access:
--
-- CREATE OR REPLACE SECRET iceberg_s3 (
--     TYPE S3, KEY_ID 'minio', SECRET 'minio123',
--     REGION 'us-east-1', ENDPOINT 'minio:9000',
--     URL_STYLE 'path', USE_SSL false
-- );
-- ATTACH '' AS lake (TYPE ICEBERG, ENDPOINT 'http://iceberg-rest:8181', AUTHORIZATION_TYPE 'none');
-- SELECT * FROM lake.gold.daily_trading_summary;
